### ISSUE TITLE
Empty library url breaks the old mc launcher

### ISSUE THREAD

**Issue by skmedix** [MinecraftForge/Installer#43]
**Cause of problem:**
![image](https://user-images.githubusercontent.com/3246162/52899650-c2196d80-31ec-11e9-9edd-e8f65120808b.png)

**Stacktrace from the launcher:**
```
com.google.gson.JsonSyntaxException: java.net.MalformedURLException: no protocol: 
	at com.google.gson.Gson.fromJson(Gson.java:818) ~[launcher.1.6.91.jar:1.6.91]
	at com.google.gson.Gson.fromJson(Gson.java:768) ~[launcher.1.6.91.jar:1.6.91]
	at com.google.gson.Gson.fromJson(Gson.java:717) ~[launcher.1.6.91.jar:1.6.91]
	at com.google.gson.Gson.fromJson(Gson.java:689) ~[launcher.1.6.91.jar:1.6.91]
	at net.minecraft.launcher.updater.LocalVersionList.refreshVersions(LocalVersionList.java:46) [launcher.1.6.91.jar:1.6.91]
	at net.minecraft.launcher.updater.MinecraftVersionManager.refreshVersions(MinecraftVersionManager.java:60) [launcher.1.6.91.jar:1.6.91]
```
---

**Question:**
~~Is `downloads` block~~ Is `url` really needed if we don't download the forge jar?
_(Edit: I guess I need coffee. I wanted to ask about empty url, but I wrote about `downloads` block 😅)_

**Solutions:**
1. ~~Don't include `downloads` block~~
2. Don't include empty `url`

**Comment by Niko-sk2x** [comment]
The downloads section may be needed to be able to specify sha1 and size. Without that, the launcher will try to use any jar that there is, even if it's corrupted/wrong.
And I also found that if the jar is missing or incorrect, the new launcher gets stuck trying to download the non-existing url. So that is another reason i think it should be fixed.

**Comment by LexManos** [comment]
Breaking automatic downloads is the entire point of using a empty url, you should be able to load it just fine in the modern launcher. So I don't see this as being a real issue.
There is however a different behavior when using null vs empty in the new launcher. Which is why we are not using null.

The only potential solution would be to supply a valid syntax, but invalid server. Something like "http://this.will.never.download/" but that is just as dirty. And would need some hacks in other projects to make it work.

**Comment by tterrag1098** [comment]
I'm wondering if it would be possible to use a `file://` scheme here to make it happy. I'll give it a shot some time.

**Comment by GoryMoon** [comment]
This also break the new native launcher beta, it doesn't allow the url in a library to be empty and won't launch the game. [Twitter announcement of the new version.](https://twitter.com/slicedlime/status/1139554652083691520)
It works in the stable version of the launcher.

To get the beta version, go to the settings, click the beta checkbox and relaunch.
The [1.14.2-forge-26.0.25.json](https://gist.github.com/GoryMoon/2a52adba20b5f01cabaae5d2ee4e9c30) is unmodified from a fresh install of forge. 

Filling the empty url field with anything, as long as it's not empty, enables the launcher to start minecraft.

<img width="1375" alt="Screenshot 2019-06-14 at 18 04 11" src="https://user-images.githubusercontent.com/987002/59522572-4942cd80-8ecf-11e9-9649-77c14e310a9b.png">

**Comment by LexManos** [comment]
This is a known issue, that I warned peter about last night but they deployed the beta anyways.
There is NOT a work around that is functional right now, as they screw up a lot more then just the downloader.

Hopefully Mojang will actually start to listen to us when we request/state things that we need. Once they fix their end, i'll update you guys here.
For now, DO NOT USE THE LAUNCHER BETA.

**Comment by LexManos** [comment]
Today's beta no longer errors on empty URLs, and fixes the classpath ordering
So the beta should work fine with Forge again.

**Comment by bs2609** [comment]
> And I also found that if the jar is missing or incorrect, the new launcher gets stuck trying to download the non-existing url.

Is this not still an issue?

**Comment by LexManos** [comment]
I was able to launch Forge just fine, no idea what edge cases exist.
Still nothing we can fix on our end. The hope is to get the launcher team to give us some control we've been asking for for years. So we no longer have to use these hacky solutions.
