### ISSUE TITLE
Java8u51 produces different outputs when patching

### ISSUE THREAD

**Issue by ichttt** [MinecraftForge/Installer#48]
Some forum posts have pointed me on this problem:
Some older java versions produce slightly different jars, but according to 7zip the content is identical, but as we compare the hash over the whole archive, the installer fails.

Screenshot of 7zip info of the jar produced with java <b>8u51</b>:
![7zFM_1lvEfxMJrD](https://user-images.githubusercontent.com/20151702/64488954-2ca7fe80-d24e-11e9-990f-d5076a2e54ec.png)
Screenshot of 7zip info of the jar produced with <b>latest</b> java:
![7zFM_oV3nHC4No3](https://user-images.githubusercontent.com/20151702/64488972-582ae900-d24e-11e9-9f83-547281f04252.png)
Here are both files (in case anyone wants to dig deeper what the diff is)
[forge 28.0.100 both files.zip](https://github.com/MinecraftForge/Installer/files/3587641/forge.28.0.100.both.files.zip)
In any case, I suggest comparing content checksums instead of archive checksums (as 7zip does), as compression can also change with future java version

**Comment by LexManos** [comment]
We can't compare archive checksums as it's already a "unreasonable" thing to have installers check output checksums at all. 

Anyways, as discussed on Discord, I've dug into the issue. Your 'oldjava' jar does not contain the UTC timestamp 'extradata' that is written when any timestamps are set: https://github.com/openjdk/jdk/blob/master/src/java.base/share/classes/java/util/zip/ZipOutputStream.java#L431

I have verified that this is the same code that is run on j8u51, It was introduced somewhere between j7u80 and j8u2. So i am not sure exactly what you are running to get this invalid jar.

And we HAVE to set the timestamp in order to make the output jar reproducible in the first place, as by default it encode currentTime as the timestamp if it's not set.

I even ran the installer using the runtime shipped with Minecraft itself, and it output the correct jar.
Is anyone else able to reproduce this issue in any way?

**Comment by ichttt** [comment]
If we can't fix the root issue, can we include two checksums and check if either if those match? This means, that the generator has to be run for both j8 latest and j8u51.

**Comment by LexManos** [comment]
As I said, I am unable to reproduce the issue on j8u51, the code in question has existed since j8u2. So not idea how people are getting this issue.

**Comment by ichttt** [comment]
I dug I little deeper and I think I found the root issue: We currently set the time of all zip entries to 0, which is the 1.1.1970. However, the zip format default time is dos time, which begins at 1.1.1980, so if a newer java version detects an older than 1.1.1980, it writes zero to the main time and adds extended time headers, so it can express that date.
It seems like that behaviour was added in a later java version.

Still not sure why you didn't get the issue, but changing binarypatcher locally to use 1568923771531L as time, it produces the same checksum (which does not match the actual one either, because the generator needs to be updated to put the same time in). This also means that all tools in the toolchain that use setTime at one point or the other need to have their checksum generator and archive packer patched for this to work.

**Comment by LexManos** [comment]
No idea why I am not getting it either, but I can see the code that you're talking about. 
We'll have to figure out what parts of the chain use a 0 time. There is also issues using that in j8u91-122. But thats a different issue.

**Comment by LexManos** [comment]
I've updated BinPatcher, and InsatallerTools to use a time that *shouldn't* be a issue...
There may need to be something added to FG to invalidate the MergedJar during build to takeup these changes....
Maybe a MCPConfig bump...

Someone will need to test the toolchain and make a PR to Forge.
As i'm not getting the issue.

**Comment by ichttt** [comment]
Confirmed to be fixed by latest changes
