### ISSUE TITLE
Add headless client install

### ISSUE THREAD

**Issue by goof-bug** [MinecraftForge/Installer#72]
Could a `--installClient` headless option be added similar to the `--installServer` option? Preferably with an optional directory argument, if omitted it should use the autodetected path similar to the default in the GUI.

**Comment by gigaherz** [comment]
No, the lack of such an option is intentional. The forge project relies on website ads to sustain the server costs, and automated install tools that fetch from our servers would increase the cost while at the same time reducing the income.
The only reason installServer exists, is that many servers are headless (lacking a monitor and sometimes not having a gpu) at all, and it is necessary to be able to install from terminal.
